controller_list:
  - name: fake_arm_controller
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_flex_joint
      - wrist_rot_joint
  - name: fake_gripper_controller
    joints:
      - finger_joint1
      - finger_joint2